
name: scrape
on:
  schedule:
    - cron: '0 23 * * *' # Clock in at 7:00 CST everyday.
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Installed package list
        run: apt list --installed
      - name: Install all necessary packages
        run: pip install webdriver-manager selenium
      - name: Run the scraping script
        env:
          XUHAO: ${{ secrets.XUHAO }}
          MIMA: ${{ secrets.MIMA }}
        run: python scraper.py
